version: "3.9"

services:
  flask_server:
    container_name: main_flask_server
    image: tiangolo/uwsgi-nginx-flask:latest
    ports:
      - '5000:80'                                 # external port : internal port
    volumes: 
      - ./Servidor:/app                           # copy project to container
    networks: 
      backend:
        ipv4_address: 172.20.1.0

  auth_server:
    container_name: auth_flask_server
    build: 
      context: .
      dockerfile: ./Servidor/Auth_Server/Dockerfile
    ports:
      - '5005:80'
    volumes: 
      - ./Servidor/Auth_Server:/app
    environment:
      JWT_SECRET_KEY: ThisIsMyKey
    networks:
      backend:
        ipv4_address: 172.20.1.3

  service_server:
    container_name: service_flask_server
    build: 
      context: .
      dockerfile: ./Servidor/Service_Server/Dockerfile
    ports:
      - '5007:80'
    volumes: 
      - ./Servidor/Service_Server:/app
    environment:   
      JWT_SECRET_KEY: ThisIsMyKey
    networks:
      backend:
        ipv4_address: 172.20.1.5

volumes:
  auth_db:
  service_db:

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.0/16