version: "3.9"

services:
  flask_server:
    container_name: main_flask_server
    image: tiangolo/uwsgi-nginx-flask:latest
    ports:
      - '5005:88'                                 # external port : internal port
    volumes: 
      - ./Servidor:/app                           # copy project to container

  auth_database:
    container_name: auth_database
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: auth_DB
    volumes:
      - auth_db:/var/lib/mysql                  # data will be persisted here
      - ./Databases/auth_database.sql:/docker-entrypoint-initdb.d/auth_database.sql
    networks:
      backend:
        ipv4_address: 172.20.1.1
    cap_add:                                    # handle the ```mbind: Operation not permitted``` error softly
      - SYS_NICE

  auth_adminer:
    container_name: adminer_for_auth
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    networks:
      backend:
        ipv4_address: 172.20.1.2
    # check mySQL database addr (Server field): 
      # docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' <container_hash>

  auth_server:
    container_name: auth_flask_server
    build: .
    ports:
      - '5000:80'
    volumes: 
      - ./Servidor/Auth_Server:/app
    #depends_on:
    #  - auth_database
    networks:
      backend:
        ipv4_address: 172.20.1.3

volumes:
  auth_db:

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.0/16