version: "3.9"

services:
  flask_server:
    image: tiangolo/uwsgi-nginx-flask:latest
    ports:
      - '5000:80'                                 # external port : internal port
    volumes: 
      - ./Servidor:/app                           # copy project to container

  auth_server:
    build: .
    ports:
      - '5005:88'
    volumes: 
      - ./Servidor/Auth_Server:/app
    links:
      - auth_database

  auth_database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: auth_DB
    ports:
      - '3306'
    volumes:
      - auth_db:/var/lib/mysql                  # data will be persisted here
      - ./Databases/auth_database.sql:/docker-entrypoint-initdb.d/auth_database.sql
    networks:
      backend:
        ipv4_address: 172.20.1.1

  auth_adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    networks:
      backend:
        ipv4_address: 172.20.1.2
    # check mySQL database addr (Server field): 
      # docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' <container_hash>

volumes:
  auth_db:

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.0/16