from tiangolo/uwsgi-nginx-flask:latest
run /usr/local/bin/python -m pip install --upgrade pip
run pip install flask-mysqldb
run pip install flask-jwt 
run pip install flask-cors 
run pip install sqlalchemy
run pip install python-dotenv
run pip install pymysql
run pip install mysql-connector-python
run pip install mysql-connector
run pip install mysql
run pip install mysqlclient
run pip install configparser